### ISSUE TITLE
cant import it as a package in frameworks

### ISSUE THREAD

**Issue by jesvijonathan** [jesvijonathan/JOS-Animation-Library#11]
You cant import or install it as a package in frameworks, **instead you will have to embed the jos .css & .js links into your project to get it working...**

I'll update it soon to avoid confusion...

**Comment by jesvijonathan** [comment]
worked on it... & now **you can `npm install jos-animation` to add it** to your project...
   - Full auto imports (the ones where css and js are auto imported) have been disabled to not mess with your project.. & are to be manually specified in your project)
   - npm by default points to latest build including beta...
   - make use of [`https://unpkg.com/jos-animation`](https://unpkg.com/jos-animation) to manually point to a specific package 
     - https://unpkg.com/jos-animation@0.8.8/dist/jos.js or https://unpkg.com/jos-animation@0.8.8
     - https://unpkg.com/jos-animation@0.8.8/dist/jos.css
   - The package is exported depending on the environment when jos class is initialised
 
Many more, but do check in to it and also feel free to contribute to making jos imports easier

**Comment by mrleblanc101** [comment]
The import method should probably be added to the README.
I had to guess if it would work, then I confirmed by searching for "vue" in the Github issue and found this: https://github.com/jesvijonathan/JOS-Animation-Library/issues/15

**Comment by jesvijonathan** [comment]
@mrleblanc101, shiz forgot to update the Readme... I have updated the Readme with steps for installation on importing and setting up in frameworks..


For Vue.3js in particular :

- Here is an example website built using JOS : 
  - https://jos-animation.vercel.app
- You can find its implementation here in this repository : 
  - https://github.com/jesvijonathan/JOS-Animation-Playground/blob/main/src/main.js
- &few more information here on JOS Readme : 
  - https://github.com/jesvijonathan/JOS-Animation-Library?tab=readme-ov-file#frameworks
  
Thanks for notifying !
