### ISSUE TITLE
"once" is not working

### ISSUE THREAD

**Issue by fknorn** [jesvijonathan/JOS-Animation-Library#16]
**Describe the bug**
My understanding is that if the parameter "once" is set, either globally or on an element, it should only be animated "in" once, then stay there. 

**To Reproduce**
1. Load library etc.
2. Call `JOS.init({once:true})`

**Expected behavior**
Element animates in, then stays there.

**Environment:**
 - OS: any
 - Browser: chrome, safari, ...
 - Version: pretty much latest
 - jos version 0.7

**Comment by jesvijonathan** [comment]
@fknorn tx for reporting, this bug has been fixed in [`v0.8` ](https://github.com/jesvijonathan/JOS-Animation-Library/releases/tag/v0.8).

_Also, do check out the new features from this release, they might be useful_

**Comment by fknorn** [comment]
Works great, thanks so much!
