### ISSUE TITLE
AOS Anchor

### ISSUE THREAD

**Issue by tomoyanime** [jesvijonathan/JOS-Animation-Library#4]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cannot use Anchor functionality on animation library

**Describe the solution you'd like**
I want to have something similar to data-aos-anchor in AOS https://github.com/michalsnik/aos#anchor

**Comment by jesvijonathan** [comment]
Hey @tomoyanime, you feature request (Anchor mechanism) has been implemented in the latest release...
Try it out and let me know what you think about it,
Meanwhile, do <b>star</b> the project :)

**Comment by tomoyanime** [comment]
@jesvijonathan Thank you!
The Example link of Anchor on README points to "/jesvijonathan/JOS-Animation-Library/blob/master" so it would be great if you can fix it as well.

**Comment by jesvijonathan** [comment]
@tomoyanime sorry for the incomplete documentation. 
You can find an example over here [JOS-Animation-Library\dev\index.html](https://github.com/jesvijonathan/JOS-Animation-Library/blob/master/dev/index.html?plain=1#L66).

Meanwhile Imma work on properly documenting  the code 😁
