### ISSUE TITLE
Angular 16 No Animation

### ISSUE THREAD

**Issue by edavis1993** [jesvijonathan/JOS-Animation-Library#41]
I can't get this to work in Angular 16. I've installed the package and followed the steps for angular install. When I load the page my element is hidden and when I inspect the element in browser I can see the JOS attributes get added. Also if I set debugMode to true in the initializer I can see the initial "JOS values" and "JOS Initialized" print in console so it seems to be setup right. But when I scroll down nothing ever appears. Not sure what I'm missing here.

Note:
When I'm importing
import JOS from "jos-animation";
I get "Could not find a declaration file for module" so I had to create my own module declaration to resolve that issue.

I'm then using OnInit and AfterViewChecked

ngOnInit(): void {
    JOS.init({
      animation: "grow",
      debugMode: true,
      duration: 0.4,
      rootMargin: "10% 0% 40% 0%",
    });
}

ngAfterViewChecked(): void { 
  JOS.refresh(); // For every update
}

Any idea what I could be missing or is this just not compatible with Angular 16?

**Comment by edavis1993** [comment]
FYI: I'm using version 0.9.2

**Comment by jesvijonathan** [comment]
Hey @edavis1993 glad to know that you got it working with your project. 

could you contribute or share the working code snippet here, so that we can add to Readme/Docs ?

**Comment by edavis1993** [comment]
Yeah, I'm new to Angular so there might be a better way but below is what worked for me.

```
import { Component, OnInit, AfterViewInit } from '@angular/core';

import JOS from 'jos-animation';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit, AfterViewInit {

  ngOnInit(): void {
    JOS.init();
  }

  ngAfterViewInit(): void {
    JOS.refresh();
  }

}
```

For the module declaration you need to create a types\jos-animation folder at the root of the Angular project and then put an index.d.ts inside of it with the following

```
declare module 'jos-animation' {
    const JOS: any;
    export default JOS;
}
```

Then tell your project to search that folder when looking for types by adding this to your tsconfig.json


```
    "typeRoots": [
      "types",
      "node_modules/@types"
    ],
```

Note: I believe this index.d.ts file could be added into the project and declare what types are actually supported so that people wouldn't have to do it manually and to add type safety. All I'm doing is declaring an any type to get rid of the typescript errors.

Great Library by the way!

**Comment by jesvijonathan** [comment]
Thanks @edavis1993 !
